### ISSUE TITLE
Service Information

### ISSUE THREAD

**Issue by jason-a-alexander** [FractalManufacturing/OctoPrint-FractalBridge#1]
Can you provide more information about this service.  Maybe a URL to your homepage.  You seem so new Google doesn't know about you yet.

**Comment by Popeyef5** [comment]
Hi Jason! Definitely: [Fractal's home page](https://fractal.tech)

Fractal is a cloud platform for 3D printer management. It aims to help you drastically reduce the time you spend interacting with the machines and enhance the printing uptime. The key idea is the following: from the start of your 3D printing workflow (prototyping, manufacturing on demand, selling through an ecommerce, etc...) until the piece comes out of the printer, you shouldn't have to do anything yourself.

Some current cool features include:

- Automatic scheduling which minimizes human intervention and maximizes printer efficiency
- Centralized printer control
- OctoPrint support
- Automatically sending print jobs to printer
- Stock tracking

And soon we'll have much more!

You can join our [Discord](https://t.co/r6yrePkdk8?amp=1)!

**Comment by jason-a-alexander** [comment]
Thanks,  You might just want to throw this on the front page of your plugin.  I'm sure I'm not the one only interested in these details.

**Comment by Popeyef5** [comment]
Yes, I'm doing that as we speak :smile:
